# -*- coding: utf-8 -*-
"""Note content for the Apple Notes MVP.
Every fact here is lifted from the shipped AskSia bibles:
  - BUSS1020  ~/Desktop/AU/library-build/courses/buss1020/  (USyd, 123-page bible, 11 chapters)
  - ECB1101   ~/Desktop/AU/library-build/courses/ecb1101/   (Monash, exam bible; visual = Ada's real /studyguide output 2026-08-28)
  - SAT       ~/Desktop/Test Prep/sat-bible-build/golden-sat/ (live hub + Algebra child page)
Section kinds: facts | tree | formulas | terms | traps | ritual | table
"""

SITE = "https://mark-sia.github.io/asksia-notes-lab"

NOTES = [
    # ────────────────────────────────────────────────────────────────── BUSS1020
    dict(
        id="buss1020",
        emoji="📊",
        code="BUSS1020",
        title="BUSS1020 Final Exam Cheat-Note",
        title_zh="BUSS1020 期末速查",
        subtitle="Quantitative Business Analysis · University of Sydney",
        uni="University of Sydney", uni_short="USyd", term="S1 2026", discipline="Statistics",
        source_name="BUSS1020 Course Bible", source_pages=123, source_chapters=11,
        source_url="https://www.asksia.ai/explore/au-usyd/buss1020",
        pdf_label="BUSS1020 Bible · 123-page PDF",
        stats=[("12","formulas"),("10","key terms"),("9","exam traps"),("1","decision tree")],
        hero_line="123 pages → 1 note. Every formula, every trap, the test-picking tree.",
        hero_line_zh="123 页 bible 压成 1 条备忘录：全部公式、全部陷阱、选检验决策树。",
        handwriting="Formula sheet is GIVEN — your edge is speed + picking the right test ✎",
        sections=[
            dict(kind="facts", emoji="📌", title="Exam facts · 考试事实", tone="yellow", items=[
                ("Final exam", "40% · closed book · 120 min + 10 min reading"),
                ("Paper", "18 MCQ × 2 marks + 5 written questions = 100 marks"),
                ("Also counts", "MyLab homework 15% · in-semester test 20% · group assignment 25%"),
                ("The edge", "Formula sheet is provided → marks come from fast, correct application, not memory"),
            ]),
            dict(kind="tree", emoji="🧭", title="Which test do I use? · 选检验决策树", tone="blue", steps=[
                ("One mean, σ known", "Z = (X̄ − μ₀) / (σ/√n)"),
                ("One mean, σ unknown", "t = (X̄ − μ₀) / (S/√n) · df = n − 1"),
                ("One proportion", "Z = (p − π₀) / √[π₀(1−π₀)/n]  ← use π₀, not p"),
                ("Two means · paired (\"before/after\", same subjects)", "t on the differences D · df = n − 1"),
                ("Two means · independent, equal variances", "pooled t · df = n₁ + n₂ − 2"),
                ("Two means · independent, unequal variances", "separate-variance t (Welch df)"),
                ("Two proportions", "Z with pooled p̄ = (X₁+X₂)/(n₁+n₂)"),
            ]),
            dict(kind="formulas", emoji="🧮", title="12 formulas · 公式", tone="red", items=[
                ("Sample SD", "S = √[ Σ(Xᵢ − X̄)² / (n − 1) ]"),
                ("Coefficient of variation", "CV = (S / X̄) × 100%"),
                ("Z-score", "Z = (X − X̄) / S"),
                ("Standard error of the mean", "SE = σ / √n"),
                ("Confidence interval", "estimate ± (critical value) × SE"),
                ("Z critical values", "90% → 1.645 · 95% → 1.96 · 98% → 2.33 · 99% → 2.58"),
                ("Sample size (mean)", "n = Z²σ² / e²  → always round UP"),
                ("Sample size (proportion)", "n = Z²π(1−π) / e²"),
                ("Binomial", "μ = nπ · σ² = nπ(1−π)"),
                ("Poisson", "μ = σ² = λ"),
                ("Regression line", "Ŷ = b₀ + b₁X · r² = SSR / SST"),
                ("Adjusted r²", "1 − (1 − r²)(n − 1)/(n − k − 1)"),
            ]),
            dict(kind="terms", emoji="🔑", title="Key terms · 关键术语（双语）", tone="purple", items=[
                ("Parameter vs statistic", "参数 vs 统计量", "Greek = population, Latin = sample"),
                ("Standard error", "标准误", "SD of the sampling distribution, σ/√n"),
                ("Central Limit Theorem", "中心极限定理", "X̄ ≈ normal when n ≥ 30, whatever the population shape"),
                ("Type I / Type II error", "第一类 / 第二类错误", "α = reject a true H₀ · β = keep a false H₀ · power = 1 − β"),
                ("p-value", "p 值", "P(statistic at least this extreme | H₀ true); reject when p < α"),
                ("Confidence interval", "置信区间", "point estimate ± margin of error"),
                ("Coefficient of variation", "变异系数", "unit-free spread, compare across scales"),
                ("Independence", "独立性", "P(A|B) = P(A)  ⇔  P(A and B) = P(A)P(B)"),
                ("Dummy variable", "虚拟变量", "0/1 predictor; coefficient = gap vs the omitted category"),
                ("Prediction vs confidence interval", "预测区间 vs 置信区间", "PI (one Y) is always WIDER than CI (mean Y)"),
            ]),
            dict(kind="traps", emoji="⚠️", title="9 exam traps · 考试陷阱", tone="rose", items=[
                "σ vs σ/√n — ONE parcel uses σ; the MEAN of 36 parcels uses σ/√n. The #1 error in the back half of the unit.",
                "Sample variance divides by (n − 1), never n.",
                "Sample-size answers ALWAYS round up, and use Z (not t) — you are planning before data exist.",
                "Proportion test SE uses the hypothesised π₀, not the sample p.",
                "\"Fail to reject\" ≠ \"accept\". Write \"insufficient evidence\", never \"H₀ is true\".",
                "\"Before and after\" / \"same subjects\" = PAIRED. Treating it as independent throws away the design.",
                "BINOM.DIST last argument: 0 = exact, 1 = cumulative. \"At least 13\" = 1 − BINOM.DIST(12, n, π, 1).",
                "Every regression coefficient: \"…holding the other variables constant\". Dummies: name the omitted category.",
                "r has the same sign as the slope; residual = actual − predicted (positive = above the line).",
            ]),
            dict(kind="ritual", emoji="✅", title="The 5-step ritual for EVERY test · 答题仪式", tone="green", steps=[
                "State H₀ and H₁ — with the parameter symbol (μ, π), never X̄ or p",
                "Choose α and the test (use the tree above)",
                "Compute the statistic — show the standard error line",
                "Critical value or p-value",
                "Conclude in business English, in context",
            ]),
        ],
    ),

    # ────────────────────────────────────────────────────────────────── SAT MATH
    dict(
        id="sat-math",
        emoji="🎯",
        code="SAT",
        title="Digital SAT Math Cheat-Note",
        title_zh="Digital SAT 数学速查",
        subtitle="Algebra · Advanced Math · PSDA · Geometry & Trig",
        uni="College Board · Digital SAT", uni_short="SAT", term="2026", discipline="Test Prep",
        source_name="The Complete SAT Bible", source_pages=9, source_chapters=9,
        source_url="https://www.asksia.ai/explore/exam/sat",
        pdf_label="SAT Bible · 9-section guide",
        stats=[("70%","of Math = Algebra + Adv"),("1.6","min per question"),("11","formulas"),("8","traps")],
        hero_line="Master the machine first: 44 questions, 70 minutes, no penalty, adaptive once.",
        hero_line_zh="先吃透考试机器本身：44 题 70 分钟、答错不扣分、每 section 只自适应一次。",
        handwriting="Never leave a blank. Flag & move. Read what is ASKED ✎",
        sections=[
            dict(kind="facts", emoji="📌", title="Test facts · 考试事实", tone="yellow", items=[
                ("Score", "400–1600 · Math 200–800 · Reading & Writing 200–800"),
                ("Math", "70 min · 44 questions (40 scored) · 2 modules × 22 Q × 35 min · ≈1.6 min/Q"),
                ("Reading & Writing", "64 min · 54 questions (50 scored) · 2 modules × 27 Q × 32 min · ≈1.2 min/Q"),
                ("Adaptive", "Module 1 routes you to an easier/harder Module 2 — once per section, sections independent"),
                ("Tools", "Desmos calculator on ALL of Math · 12-item reference sheet on screen · timer · flag"),
                ("Penalty", "None. Answer every question."),
            ]),
            dict(kind="table", emoji="🎯", title="Where the points are · 分值地图", tone="blue",
                 head=("Domain", "Scored Qs", "Read"),
                 rows=[
                    ("Algebra", "13–15 / 40", "linear eq., systems, inequalities"),
                    ("Advanced Math", "13–15 / 40", "quadratics, nonlinear functions, equivalent expressions"),
                    ("Problem-Solving & Data", "≈ 6–7", "ratios, %, units, probability, tables & graphs"),
                    ("Geometry & Trig", "≈ 5–6", "smallest, most formula-driven"),
                 ],
                 foot="Algebra + Advanced Math ≈ 70% of the Math score → they earn the most prep time."),
            dict(kind="formulas", emoji="🧮", title="Formulas to know cold · 必背公式", tone="red", items=[
                ("Slope", "m = (y₂ − y₁) / (x₂ − x₁)"),
                ("Slope-intercept · point-slope", "y = mx + b  ·  y − y₁ = m(x − x₁)"),
                ("Parallel · perpendicular", "equal slopes · negative-reciprocal slopes"),
                ("Quadratic formula", "x = [−b ± √(b² − 4ac)] / 2a"),
                ("Discriminant", "b² − 4ac  → >0 two roots · =0 one · <0 none"),
                ("Vertex form", "y = a(x − h)² + k · axis x = −b/2a"),
                ("Zero-product rule", "(x − p)(x − q) = 0 ⇒ x = p or q"),
                ("Exponential model", "y = a(1 + r)ᵗ  (growth) · y = a(1 − r)ᵗ (decay)"),
                ("Systems", "one solution · none (parallel) · infinite (same line)"),
                ("Inequalities", "flip the sign ONLY when × or ÷ by a negative"),
                ("Word problems", "Total = constant + rate × variable → solve → substitute back"),
            ]),
            dict(kind="terms", emoji="🔑", title="Key terms · 关键术语（双语）", tone="purple", items=[
                ("Balance principle", "等式平衡原则", "whatever you do to one side, do to the other"),
                ("Multistage adaptive (MST)", "多阶段自适应", "routed once per section, not per question"),
                ("Student-produced response", "自填答案题", "type it: fractions/decimals ok · no %, $, commas"),
                ("Equivalent expressions", "等价表达式", "a rewrite (distribute, FOIL, factor) — not something you solve"),
                ("Extraneous solution", "增根", "appears after squaring/clearing fractions — always check back"),
                ("Operational question", "计分题", "90 of 98 count; 8 are unscored pretest items"),
            ]),
            dict(kind="traps", emoji="⚠️", title="8 traps · 陷阱", tone="rose", items=[
                "Read what is ASKED: if it wants 6x − 3, solve for 6x − 3 directly, not x.",
                "SPR answers: no percent sign, dollar sign or commas. 3/4 or 0.75 both fine.",
                "Squared both sides or cleared a fraction? Check for extraneous roots.",
                "Inequality sign flips only on × or ÷ by a negative — not on adding a negative.",
                "\"No solution\" = parallel lines (same slope, different intercept); \"infinitely many\" = the same line.",
                "Questions run roughly easy → hard inside a module: bank seconds early to protect the back.",
                "Adaptive panic: a hard Module 2 means Module 1 went WELL. Keep going.",
                "The reference sheet has gaps (no quadratic formula, no slope) — those are yours to memorise.",
            ]),
            dict(kind="ritual", emoji="✅", title="Test-day pacing · 考场节奏", tone="green", steps=[
                "R&W first (64 min) → 10-min break → Math (70 min)",
                "Set the module clock: 22 Q in 35 min, checkpoint at Q11 = 17 min",
                "Stuck > 90 s → flag, guess, move on; come back with leftover time",
                "Desmos for graphs & systems; type equations, read the intersection",
                "Last 2 minutes: every flagged question gets an answer — no blanks",
            ]),
        ],
    ),

    # ────────────────────────────────────────────────────────────────── ECB1101
    dict(
        id="ecb1101",
        emoji="📈",
        code="ECB1101",
        title="ECB1101 Micro Exam Cheat-Note",
        title_zh="ECB1101 微观期末速查",
        subtitle="Introductory Microeconomics · Monash University",
        uni="Monash University", uni_short="Monash", term="S1 2026", discipline="Economics",
        source_name="ECB1101 Exam Bible", source_pages=23, source_chapters=9,
        source_url="https://www.asksia.ai/explore/au-monash/ecb1101",
        pdf_label="ECB1101 Bible · PDF",
        visual="ecb1101-visual.jpg",   # Sia-generated /studyguide from the bible PDF (Ada, 2026-08-28)
        visual_caption="Sia drew this from the ECB1101 Bible PDF (/studyguide) — 4 models, the memory loop, the weak spot.",
        stats=[("11","formulas"),("1","Sia visual"),("9","traps"),("5","step memory loop")],
        hero_line="Every graph, every model, every mark — plus the one-page visual Sia drew from the bible.",
        hero_line_zh="每张图、每个模型、每一分 —— 外加 Sia 从 bible 里画出来的一页视觉图。",
        handwriting="Section C: label EVERY axis, curve, shift arrow, equilibrium & shaded area ✎",
        sections=[
            dict(kind="facts", emoji="📌", title="Exam facts · 考试事实", tone="yellow", items=[
                ("Final exam", "50% · three sections"),
                ("Section C", "the drawing section — diagrams with every area labelled"),
                ("First marks on any policy question", "the free-market equilibrium: set Qd = Qs → (P*, Q*) → clean labelled diagram"),
                ("Notation", "Monash uses TS for total surplus and e for the external effect"),
            ]),
            dict(kind="tree", emoji="🔁", title="Quick memory loop · 五步记忆环", tone="blue", steps=[
                ("1 · Set Qd = Qs", "solve for P*, Q*"),
                ("2 · Find elasticity", "midpoint method → |E| > 1 elastic · < 1 inelastic · = 1 unit"),
                ("3 · Draw CS / PS", "CS above price under demand · PS below price above supply"),
                ("4 · Add the policy wedge", "tax t · ceiling · floor · externality e"),
                ("5 · Label + shade DWL", "½ × t × (Q₁ − Q₂)"),
            ]),
            dict(kind="formulas", emoji="🧮", title="11 formulas · 公式", tone="red", items=[
                ("Consumer surplus", "CS = ½ × Q* × (Pmax − P*)"),
                ("Producer surplus", "PS = ½ × Q* × (P* − Pmin)"),
                ("Total surplus", "TS = CS + PS — maximised at competitive Q*"),
                ("Tax wedge", "Pb − Ps = t"),
                ("Tax revenue · DWL", "t × Q₂  ·  DWL = ½ × t × (Q₁ − Q₂)"),
                ("PED (midpoint)", "(ΔQ / avg Q) ÷ (ΔP / avg P)"),
                ("Total-revenue rule", "inelastic → raise P raises TR · elastic → raise P lowers TR"),
                ("Monopoly MR", "P = a − bQ ⇒ MR = a − 2bQ · profit-max at MR = MC, price off demand"),
                ("Perfect competition", "P = MR = AR · produce at P = MC · shut down if P < min AVC · LR: P = min ATC"),
                ("Costs", "ATC = AVC + AFC · MC = ΔTC/ΔQ = w / MP"),
                ("Opportunity cost (table)", "units of the OTHER good given up ÷ units of this good gained"),
            ]),
            dict(kind="terms", emoji="🔑", title="Key terms · 关键术语（双语）", tone="purple", items=[
                ("Movement along vs shift", "沿曲线移动 vs 曲线移动", "own price → along · any shifter → shift"),
                ("Comparative advantage", "比较优势", "lower opportunity cost — THIS decides who specialises"),
                ("Deadweight loss", "无谓损失", "surplus destroyed when Q ≠ Q*, gained by no one"),
                ("Tax incidence", "税收归宿", "the less-elastic side bears more, whoever writes the cheque"),
                ("Externality (e)", "外部性", "social cost = WTS + e · social value = WTP + e"),
                ("Public good vs common resource", "公共品 vs 公共资源", "non-rival + non-excludable (free-rider) · rival + non-excludable (commons)"),
                ("Long-run tangency", "长期相切", "monopolistic competition: P = ATC, profit 0, excess capacity"),
            ]),
            dict(kind="traps", emoji="⚠️", title="9 exam traps · 考试陷阱", tone="rose", items=[
                "Absolute advantage does NOT decide specialisation — comparative advantage (opportunity cost) does.",
                "A price ceiling binds only BELOW P* (shortage); a floor binds only ABOVE P* (surplus). Trade happens on the short side.",
                "Tax incidence = relative elasticity, never \"who pays the government\".",
                "Shut-down uses AVC (short run); exit uses ATC (long run). Don't swap them.",
                "Monopoly: MR < P. Read Q from MR = MC, then the PRICE off the demand curve.",
                "Demand shift moves P* and Q* the same way; supply shift moves them opposite ways; both shift → one is ambiguous.",
                "Sunk costs are irrelevant to a forward-looking decision — they are not an opportunity cost.",
                "Revenue (rectangle) is transferred, not lost; only the DWL triangle is lost.",
                "Section C: a diagram without labels earns nothing. Axes, curves, arrows, equilibrium, shaded areas.",
            ]),
            dict(kind="ritual", emoji="✅", title="Externality exam move · 外部性答题步骤", tone="green", steps=[
                "Identify the failure: externality (which side? which sign?), public good, or common resource",
                "Draw the social curve a distance e from the private one (above S for external cost, above D for external benefit)",
                "Read Q_market vs Q* → over- or under-production",
                "Corrective tax or subsidy = e per unit → back to Q*",
                "Shade the DWL triangle between the two quantities",
            ]),
        ],
    ),
]
